### ISSUE TITLE
conflict with redmine_pivottable

### ISSUE THREAD

**Issue by archonwang** [charleneChen/issues_tree_table#7]
@charleneChen ,
open the pivottable occur 500 error, please check it.  Thanks.
https://github.com/deecay/redmine_pivot_table.git

related issues:
https://github.com/deecay/redmine_pivot_table/issues/38

**Comment by archonwang** [comment]
error log

```
A NoMethodError occurred in pivottables#index:
 
  undefined method `count' for nil:NilClass
  plugins/redmine_issues_tree_view/lib/issue_query_patch.rb:15:in `issues'
 
 
-------------------------------
Request:
-------------------------------
 
* URL : http://192.168.1.41/projects/zmss/pivottables
  * HTTP Method: GET
  * IP address : 192.168.60.238
  * Parameters : {"controller"=>"pivottables", "action"=>"index", "project_id"=>"zmss"}
  * Timestamp  : 2017-04-12 08:45:49 UTC
  * Server : jira
  * Rails root : /opt/redmine-3.3
  * Process: 15640
 
-------------------------------
Session:
-------------------------------
 
  * session id: "efb7eefca976533d0e1e8e8c0c0e7075"
  * data: {"session_id"=>"efb7eefca976533d0e1e8e8c0c0e7075",
   "user_id"=>8,
   "tk"=>"e60891dc0a68a37297c75ef1664a6fd61d7323fe",
   "sudo_timestamp"=>1491964677,
   "_csrf_token"=>"JiKVxp6TUv53GQr9gjXPTKFwEO6vB/X4Db2fQmQTGhA=",
   "recent_projects"=>[37, 5, 2, 1, 13],
   "access_count_table"=>{30=>1},
   "users_index_sort"=>"login",
   "timelog_index_sort"=>"spent_on:desc",
   "timesheets_show_sort"=>"spent_on:desc",
   "current_timesheet"=>
    {:query=>
      {:filters=>{"spent_on"=>{:operator=>"*", :values=>[""]}},
       :group_by=>nil,
       :column_names=>nil,
       :totalable_names=>[:hours]}},
   "query"=>
    {:project_id=>5,
     :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}},
     :group_by=>"parent",
     :column_names=>nil,
     :totalable_names=>[:estimated_hours, :spent_hours]}}
 
-------------------------------
Environment:
-------------------------------
 
  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : */*
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8,en;q=0.6
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : wl_auth=client_id=0000000040145A19&status=unchecked; _ga=GA1.1.383030868.1491968739; _redmine_session=WDJ2UWRQN2hmSjl1QmljcU9UVU1pRFhsSFZIVEY5OGE4aGJPOGNJdFZrRVFsYlU2QTBoNE9iYi9jOHJ0VkJBdUk5d0RmN2FRNDZ0NUJmN2RpSDljN3VwQlMrV0JRWUpyY0EreWNhM0t0YklJeFMrRlBPTi9sWGJoNDV2OUd3S0RRVUYxL3MwaDRMU3ZVNStMUnJCWWw3cnBEbXVzOHoyNkFYRVc3cmJHczJGQlhKR3BZeDZhSE5DdzNINjhvT0ZEQXcvYjE4dWtuMDVLcWRtQWUrLzJsdEZPSXA4MldndGtFYmlwM0pRWlVqRVdQTmV4S2JMMVUwRTVQdmtKSE8ySXl2TEs3Mkd2NkxQbzNvQSs5anBjbXBBOVpqSWwwT1c1RUF5ckdpYWhoRU8wWFdLZVh0Ynl2K2EvQW1MTmJRcU1PWk9saDNQaFFzZmRvK2dOVmxVUW5TWjBSUm82OXNlUC90dHdxYUpZN1dDZWNCWGRWeDN5OGZESUI3MThNNzE2SzJrVmtlRytLSHNDN3MxU0tmVkhiVXZ3VW5TdE5DTjAwc2NOdkNabGIwU3dzZ2xxRWhQTHNjL0NEU1FPTHR5R09DcWxHVlgrNEszR0pvd2MvUmk3WWp1ZjFtaVZNV05XWVc2c25DMlhpYnFGeUx4ZWxWKytrN3pHaDRGTGVHYVZiL09BK0pTNzduQTJhSElPUkxnMkVVS2UwckkyZXF6L2ZDSUZOOEFJekp0SVNkckNCb1ZRcnluWitqOGtkNUY2S2RwVUN6dk5jNzNvRmprTnJUeUpGYUc1bmlpRk5zcWhvRmlDNVFDTkpwc0R3T0tBeDZMcW03T3A3M2V6S2w1KzZ4ZnpYZGNDbWlubTg5ajFiQXFjOXV0NGNoMk1aUmhCN0RJRDhEWVEyN0xTRUNTVWtRUERvR2F1Mk5oaXdGZDEyM012NStBWU9QVTk0QzI1MUNBUTJrV0UrZCsram1ydmpCdnVRRmM3UHJuN3pYR004bFBaTnNvMFZ6dURWeWZkLS1hS0Fuc3lkZUlIMzVMUmxMZkN5SFl3PT0%3D--b72f4f6bd56bd9553a1ce48d960d2e83203e3f6f
  * HTTP_HOST                                      : 192.168.1.41
* HTTP_REFERER : http://192.168.1.41/projects/zmss/pivottables
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest
  * ORIGINAL_FULLPATH                              : /projects/zmss/pivottables
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /projects/zmss/pivottables
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 192.168.60.238
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /projects/zmss/pivottables
  * REQUEST_URI                                    : /projects/zmss/pivottables
  * ROUTES_15794000_SCRIPT_NAME                    :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : 192.168.1.41
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
  * action_controller.instance                     : #<PivottablesController:0x007f521898e218>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00000004cf4028>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f52188f7f98>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x00000003151b68>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x00000001df71a8>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 192.168.60.238
  * action_dispatch.request.accepts                : [#<Mime::Type:0x007f521898cf08 @synonyms=[], @symbol=nil, @string="*/*", @hash=2114508088111681411>]
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x007f521898cf08 @synonyms=[], @symbol=nil, @string="*/*", @hash=2114508088111681411>]
  * action_dispatch.request.parameters             : {"controller"=>"pivottables", "action"=>"index", "project_id"=>"zmss"}
  * action_dispatch.request.path_parameters        : {:controller=>"pivottables", :action=>"index", :project_id=>"zmss"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"efb7eefca976533d0e1e8e8c0c0e7075", "user_id"=>8, "tk"=>"e60891dc0a68a37297c75ef1664a6fd61d7323fe", "sudo_timestamp"=>1491964677, "_csrf_token"=>"JiKVxp6TUv53GQr9gjXPTKFwEO6vB/X4Db2fQmQTGhA=", "recent_projects"=>[37, 5, 2, 1, 13], "access_count_table"=>{30=>1}, "users_index_sort"=>"login", "timelog_index_sort"=>"spent_on:desc", "timesheets_show_sort"=>"spent_on:desc", "current_timesheet"=>{:query=>{:filters=>{"spent_on"=>{:operator=>"*", :values=>[""]}}, :group_by=>nil, :column_names=>nil, :totalable_names=>[:hours]}}}
  * action_dispatch.request_id                     : e75214b2-0ec0-4e27-8b0d-6df903d29ae4
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000001e1fea0>
  * action_dispatch.secret_key_base                : 59dda17a42803617f96151518b9aeecb94e132c6f140123f1982e1c8ae15d0103ffa854c4d8b0019
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * async.callback                                 : #<Method: Thin::Connection#post_process>
  * async.close                                    : #<EventMachine::DefaultDeferrable:0x007f5218b82c90>
  * rack.errors                                    : #<IO:0x000000006f95a0>
  * rack.input                                     : #<StringIO:0x007f5218b83938>
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {"wl_auth"=>"client_id=0000000040145A19&status=unchecked", "_ga"=>"GA1.1.383030868.1491968739", "_redmine_session"=>"WDJ2UWRQN2hmSjl1QmljcU9UVU1pRFhsSFZIVEY5OGE4aGJPOGNJdFZrRVFsYlU2QTBoNE9iYi9jOHJ0VkJBdUk5d0RmN2FRNDZ0NUJmN2RpSDljN3VwQlMrV0JRWUpyY0EreWNhM0t0YklJeFMrRlBPTi9sWGJoNDV2OUd3S0RRVUYxL3MwaDRMU3ZVNStMUnJCWWw3cnBEbXVzOHoyNkFYRVc3cmJHczJGQlhKR3BZeDZhSE5DdzNINjhvT0ZEQXcvYjE4dWtuMDVLcWRtQWUrLzJsdEZPSXA4MldndGtFYmlwM0pRWlVqRVdQTmV4S2JMMVUwRTVQdmtKSE8ySXl2TEs3Mkd2NkxQbzNvQSs5anBjbXBBOVpqSWwwT1c1RUF5ckdpYWhoRU8wWFdLZVh0Ynl2K2EvQW1MTmJRcU1PWk9saDNQaFFzZmRvK2dOVmxVUW5TWjBSUm82OXNlUC90dHdxYUpZN1dDZWNCWGRWeDN5OGZESUI3MThNNzE2SzJrVmtlRytLSHNDN3MxU0tmVkhiVXZ3VW5TdE5DTjAwc2NOdkNabGIwU3dzZ2xxRWhQTHNjL0NEU1FPTHR5R09DcWxHVlgrNEszR0pvd2MvUmk3WWp1ZjFtaVZNV05XWVc2c25DMlhpYnFGeUx4ZWxWKytrN3pHaDRGTGVHYVZiL09BK0pTNzduQTJhSElPUkxnMkVVS2UwckkyZXF6L2ZDSUZOOEFJekp0SVNkckNCb1ZRcnluWitqOGtkNUY2S2RwVUN6dk5jNzNvRmprTnJUeUpGYUc1bmlpRk5zcWhvRmlDNVFDTkpwc0R3T0tBeDZMcW03T3A3M2V6S2w1KzZ4ZnpYZGNDbWlubTg5ajFiQXFjOXV0NGNoMk1aUmhCN0RJRDhEWVEyN0xTRUNTVWtRUERvR2F1Mk5oaXdGZDEyM012NStBWU9QVTk0QzI1MUNBUTJrV0UrZCsram1ydmpCdnVRRmM3UHJuN3pYR004bFBaTnNvMFZ6dURWeWZkLS1hS0Fuc3lkZUlIMzVMUmxMZkN5SFl3PT0=--b72f4f6bd56bd9553a1ce48d960d2e83203e3f6f"}
  * rack.request.cookie_string                     : wl_auth=client_id=0000000040145A19&status=unchecked; _ga=GA1.1.383030868.1491968739; _redmine_session=WDJ2UWRQN2hmSjl1QmljcU9UVU1pRFhsSFZIVEY5OGE4aGJPOGNJdFZrRVFsYlU2QTBoNE9iYi9jOHJ0VkJBdUk5d0RmN2FRNDZ0NUJmN2RpSDljN3VwQlMrV0JRWUpyY0EreWNhM0t0YklJeFMrRlBPTi9sWGJoNDV2OUd3S0RRVUYxL3MwaDRMU3ZVNStMUnJCWWw3cnBEbXVzOHoyNkFYRVc3cmJHczJGQlhKR3BZeDZhSE5DdzNINjhvT0ZEQXcvYjE4dWtuMDVLcWRtQWUrLzJsdEZPSXA4MldndGtFYmlwM0pRWlVqRVdQTmV4S2JMMVUwRTVQdmtKSE8ySXl2TEs3Mkd2NkxQbzNvQSs5anBjbXBBOVpqSWwwT1c1RUF5ckdpYWhoRU8wWFdLZVh0Ynl2K2EvQW1MTmJRcU1PWk9saDNQaFFzZmRvK2dOVmxVUW5TWjBSUm82OXNlUC90dHdxYUpZN1dDZWNCWGRWeDN5OGZESUI3MThNNzE2SzJrVmtlRytLSHNDN3MxU0tmVkhiVXZ3VW5TdE5DTjAwc2NOdkNabGIwU3dzZ2xxRWhQTHNjL0NEU1FPTHR5R09DcWxHVlgrNEszR0pvd2MvUmk3WWp1ZjFtaVZNV05XWVc2c25DMlhpYnFGeUx4ZWxWKytrN3pHaDRGTGVHYVZiL09BK0pTNzduQTJhSElPUkxnMkVVS2UwckkyZXF6L2ZDSUZOOEFJekp0SVNkckNCb1ZRcnluWitqOGtkNUY2S2RwVUN6dk5jNzNvRmprTnJUeUpGYUc1bmlpRk5zcWhvRmlDNVFDTkpwc0R3T0tBeDZMcW03T3A3M2V6S2w1KzZ4ZnpYZGNDbWlubTg5ajFiQXFjOXV0NGNoMk1aUmhCN0RJRDhEWVEyN0xTRUNTVWtRUERvR2F1Mk5oaXdGZDEyM012NStBWU9QVTk0QzI1MUNBUTJrV0UrZCsram1ydmpCdnVRRmM3UHJuN3pYR004bFBaTnNvMFZ6dURWeWZkLS1hS0Fuc3lkZUlIMzVMUmxMZkN5SFl3PT0%3D--b72f4f6bd56bd9553a1ce48d960d2e83203e3f6f
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007f521898ffa0>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007f521898ff50>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 0]
 
-------------------------------
Backtrace:
-------------------------------
 
  plugins/redmine_issues_tree_view/lib/issue_query_patch.rb:15:in `issues'
  plugins/redmine_pivot_table/app/controllers/pivottables_controller.rb:64:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
 
```
