### ISSUE TITLE
could not work for redmine 3.4.2?

### ISSUE THREAD

**Issue by Jiangshan00001** [charleneChen/issues_tree_table#8]

**Comment by Jiangshan00001** [comment]
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"xxxx"}
  Current user: xxxx(id=4)
Completed 500 Internal Server Error in 108ms (ActiveRecord: 61.2ms)

NoMethodError (undefined method `sort_init' for #<IssuesController:0x00000008ada220>):
  plugins/redmine_issues_tree_view/lib/issues_tree_view_issues_controller_patch.rb:11:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
